version: "3.8"
services:
  # Applications

  elastic-query:
    depends_on:
      - twitter-keycloak
      - twitter-postgres
      - kafka-ui
      - broker
      - elastic
    image: "elastic-query-service"
    container_name: "elastic-query"
    ports:
      - 9001:9001
      - 8001:8001
    environment:
      - SERVER_PORT=9001
      - BPL_JVM_THREAD_COUNT=50
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8001
      - SPRING_KEYCLOAK_SERVER_URL=http://twitter-keycloak:8080
      - SPRING_KEYCLOAK_SERVER_EXTERNAL_URL=http://localhost:8080
      - ELASTIC-CONFIG_CONNECTION-URL=elastic:9200

  analytics:
    depends_on:
      - twitter-keycloak
      - twitter-postgres
      - kafka-ui
      - broker
      - elastic
    image: "analytics-service"
    container_name: "analytics"
    ports:
      - 9002:9002
      - 8002:8002
    environment:
      - SERVER_PORT=9002
      - BPL_JVM_THREAD_COUNT=50
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8002
      - SPRING_KEYCLOAK_SERVER_URL=http://twitter-keycloak:8080
      - SPRING_KEYCLOAK_SERVER_EXTERNAL_URL=http://localhost:8080


  kafka-streams:
    depends_on:
      - twitter-keycloak
      - twitter-postgres
      - kafka-ui
      - broker
      - elastic
    image: "kafka-streams-service"
    container_name: "kafka-streams"
    ports:
      - 9003:9003
      - 8003:8003
    environment:
      - SERVER_PORT=9003
      - BPL_JVM_THREAD_COUNT=50
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8003
      - SPRING_KEYCLOAK_SERVER_URL=http://twitter-keycloak:8080
      - SPRING_KEYCLOAK_SERVER_EXTERNAL_URL=http://localhost:8080

  twitter-to-kafka:
    depends_on:
      - twitter-keycloak
      - twitter-postgres
      - kafka-ui
      - broker
      - elastic
    image: "twitter-to-kafka-service"
    container_name: "twitter-to-kafka"
    ports:
      - 9004:9004
      - 8004:8004
    environment:
      - SERVER_PORT=9004
      - BPL_JVM_THREAD_COUNT=50
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8004
      - SPRING_KEYCLOAK_SERVER_URL=http://twitter-keycloak:8080
      - SPRING_KEYCLOAK_SERVER_EXTERNAL_URL=http://localhost:8080

  kafka-to-elastic:
    depends_on:
      - twitter-keycloak
      - twitter-postgres
      - kafka-ui
      - twitter-to-kafka
      - broker
      - elastic
    image: "kafka-to-elastic-service"
    container_name: "kafka-to-elastic"
    ports:
      - 9005:9005
      - 8005:8005
    environment:
      - SERVER_PORT=9005
      - BPL_JVM_THREAD_COUNT=50
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8005
      - SPRING_KEYCLOAK_SERVER_URL=http://twitter-keycloak:8080
      - SPRING_KEYCLOAK_SERVER_EXTERNAL_URL=http://localhost:8080
      - ELASTIC-CONFIG_CONNECTION-URL=elastic:9200
  
  gateway:
    depends_on:
      - twitter-keycloak
      - twitter-redis
      - kafka-ui
      - broker
      - elastic
    image: "gateway-service"
    container_name: "gateway"
    ports:
      - 9000:9000
      - 8000:8000
    environment:
      - SERVER_PORT=9000
      # Buildpacks environment variable to enable debug through a socket on port 8000
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8000
      - ELASTIC_QUERY_SERVICE_URL=http://elastic-query:9001
      - ANALYTICS_SERVICE_URL=http://analytics:9002
      - KAFKA_STREAMS_SERVICE_URL=http://kafka-streams:9003
      - SPRING_REDIS_HOST=twitter-redis
      - SPRING_KEYCLOAK_SERVER_URL=http://twitter-keycloak:8080
      - SPRING_KEYCLOAK_SERVER_EXTERNAL_URL=http://localhost:8080
  
  # Backing Services

  twitter-postgres:
    image: "postgres:14.4"
    container_name: "twitter-postgres"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin

  twitter-redis:
    image: "redis:7.0"
    container_name: "twitter-redis"
    ports:
      - 6379:6379

  keycloak-postgres:
    image: postgres:15.3
    container_name: keycloak-postgres
    ports:
      - "5433:5433"
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: "pg_isready -U postgres"
  
  twitter-keycloak:
    image: quay.io/keycloak/keycloak:${KEYCLOAK_VERSION}
    container_name: twitter-keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL_HOST=keycloak-postgres
      - KC_DB_URL_DATABASE=keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=password
      - KC_DB_PORT=5433
      - KC_HEALTH_ENABLED=true
    ports:
      - "8080:8080"
    command: start-dev
    depends_on:
      - keycloak-postgres
    healthcheck:
      test: "curl -f http://twitter-keycloak:8080/health/ready || exit 1"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.1.0
    platform: linux/amd64
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      KAFKA_OPTS: "-Dzookeeper.4lw.commands.whitelist=ruok"
    volumes:
      - "./volumes/zookeeper/data:/var/lib/zookeeper/data"
      - "./volumes/zookeeper/transactions:/var/lib/zookeeper/log"

  broker:
    image: confluentinc/cp-server:7.1.0
    platform: linux/amd64
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker:29092
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_METRICS_ENABLE: 'true'
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'
    volumes:
      - "./volumes/kafka/broker:/var/lib/kafka/data"
    healthcheck:
      test: ["CMD", "kafka-topics.sh", "--list", "--zookeeper", "zookeeper:2181"]
      interval: 10s
      timeout: 10s
      retries: 5

  schema-registry:
    image: confluentinc/cp-schema-registry:7.1.0
    platform: linux/amd64
    hostname: schema-registry
    container_name: schema-registry
    depends_on:
      - zookeeper
      - broker
    ports:
      - "8081:8081"
    environment:
      SERVER_PORT: 8081
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: 'zookeeper:2181'
      SCHEMA_REGISTRY_LISTENERS: http://schema-registry:8081
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://broker:29092,LISTENER_LOCAL://localhost:9092
      SCHEMA_REGISTRY_DEBUG: 'true'


  init-kafka:
    image: confluentinc/cp-kafka:7.1.0
    platform: linux/amd64
    depends_on:
      - schema-registry
      - broker
      - zookeeper
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      # block until kafka is reachable
      kafka-topics --bootstrap-server broker:29092 --list

      # echo -e 'Deleting kafka topics'
      # kafka-topics --bootstrap-server broker:29092 --topic twitter-topic --delete --if-exists
      # kafka-topics --bootstrap-server broker:29092 --topic twitter-analytics-topic --delete --if-exists

      echo -e 'Creating kafka topics'
      kafka-topics --bootstrap-server broker:29092 --create --if-not-exists --topic twitter-topic --replication-factor 1 --partitions 1
      kafka-topics --bootstrap-server broker:29092 --create --if-not-exists --topic twitter-analytics-topic --replication-factor 1 --partitions 1

      echo -e 'Successfully created the following topics:'
      kafka-topics --bootstrap-server broker:29092 --list
      "


  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - init-kafka
    hostname: kafka-ui
    container_name: kafka-ui
    ports:
      - "8082:8082"
    environment:
      - SERVER_PORT=8082
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=broker:29092
      - DYNAMIC_CONFIG_ENABLED=true

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION:-latest}
    hostname: elastic
    container_name: elastic
    environment:
      - node.name=elastic
      - cluster.name=es-twitter-cluster
      - discovery.seed_hosts=elastic
      - cluster.initial_master_nodes=elastic
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - "./volumes/elastic:/usr/share/elasticsearch/data"
    ports:
      - 9200:9200